# Fitting and predicting: estimator basics

In [115]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
X = [[ 1,  2,  3], 
     [11, 12, 13]]
y = [0, 1]  
clf.fit(X, y)
RandomForestClassifier(random_state=0)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [116]:
from sklearn import svm
from sklearn import datasets
from numpy import array


In [117]:
clf.predict(X) 
array([0, 1])
clf.predict([[4, 5, 6], [14, 15, 16]])  
array([0, 1])

array([0, 1])

# Transformers and pre-processors

In [118]:
from sklearn.preprocessing import StandardScaler
X = [[0, 15],
     [1, -10]]
StandardScaler().fit(X).transform(X)
array([[-1.,  1.],
       [ 1., -1.]])

array([[-1.,  1.],
       [ 1., -1.]])

# Pipelines: chaining pre-processors and estimators

In [114]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
pipe = make_pip(eline(
   StandardScaler(),
    LogisticRegression(random_state=0)
)
 X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
pipe.fit(X_train, y_train)
Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression(random_state=0))])
accuracy_score(pipe.predict(X_test), y_test)

SyntaxError: invalid syntax (<ipython-input-114-b60e936d58ce>, line 12)

# Model evaluation

In [107]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
X, y = make_regression(n_samples=1000, random_state=0)
lr = LinearRegression()
result = cross_validate(lr, X, y) 
result['test_score']
array([1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1.])